// Signs release builds with the Sutera key, read at build time from a
// properties file kept outside the repository:
//
//   ~/.sutera-keys/keystore.properties   (or $SUTERA_KEYSTORE_PROPERTIES)
//     storeFile=…/caregiver-release.keystore
//     storePassword=…  keyAlias=…  keyPassword=…
//
// android/ is generated by `expo prebuild`, so the signing setup lives
// here rather than in a hand-edited build.gradle that a rebuild would lose.
// With no properties file, release builds fall back to the debug key
// (installable for testing, but not updatable by a properly signed one).

const { withAppBuildGradle } = require("expo/config-plugins");

const MARKER = "// sutera-release-signing";

const releaseConfig = `
        ${MARKER}
        release {
            def propsPath = System.getenv("SUTERA_KEYSTORE_PROPERTIES") ?: "\${System.getProperty('user.home')}/.sutera-keys/keystore.properties"
            def propsFile = new File(propsPath)
            if (propsFile.exists()) {
                def props = new Properties()
                propsFile.withInputStream { props.load(it) }
                storeFile file(props['storeFile'])
                storePassword props['storePassword']
                keyAlias props['keyAlias']
                keyPassword props['keyPassword']
            }
        }`;

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    let gradle = cfg.modResults.contents;
    if (gradle.includes(MARKER)) return cfg;

    gradle = gradle.replace(/signingConfigs \{\n/, (m) => m + releaseConfig.slice(1) + "\n");

    // In the release build type only, use the release key when it was found.
    gradle = gradle.replace(
      /(release \{\n(?:\s*\/\/[^\n]*\n)*\s*)signingConfig signingConfigs\.debug/,
      "$1signingConfig signingConfigs.release.storeFile ? signingConfigs.release : signingConfigs.debug"
    );

    cfg.modResults.contents = gradle;
    return cfg;
  });
};
